### ISSUE TITLE
DataStore FromIni method missing ?

### ISSUE THREAD

**Issue by SnakeTheRipper** [Notulp/Fougerite#20]
I was too lazy to write it by myself to restore datastore settings from an ini and used the FromIni method but wasn't working. I see now on the source code that it isn't there.

https://github.com/Notulp/Fougerite/blob/master/Fougerite/Fougerite/DataStore.cs

Was that made consciously or it's a mistake ?

**Comment by mikecrews** [comment]
It was made consciously because at the time, it was a troubleshooting aid, not a means for saving/restoring the DataStore.

1.0.8 has new FromIni() and ToIni() methods which take the DataStore table name (string) and a IniParser instance as arguments.  You can use them to save/restore a DS table, but it is the plugin author's responsibility to convert non-string values when restoring from ini to DS.

**Comment by mikecrews** [comment]
https://github.com/Notulp/Fougerite/blob/master-mcmc/Fougerite/Fougerite/DataStore.cs#L24

https://github.com/Notulp/Fougerite/blob/master-mcmc/Fougerite/Fougerite/DataStore.cs#L51

**Comment by SnakeTheRipper** [comment]
Thanks for the answer.
