### ISSUE TITLE
Server.Players

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#25]
Remember the collection modification error mike?

[1/1/2015 12:06:44 PM] [Error] [Magma] Error invoking function pingcontrolCallback in DHPK plugin.
[1/1/2015 12:06:44 PM] [Exception] [ Plugin->Invoke | Plugin->OnTimerCB | TimedEvent->_timer_Elapsed | Timer->Callback | ]
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

This usually happens when someone is doing a for cycle in the Server.Players. Now, manually making a list and removing/adding the players to that list seems to avoid the error. If I remember well, you told me that this is a rust error, and If It would  be you you would have written It better. So, why not make ourselves an independent list?

**Comment by mikecrews** [comment]
Turns out that PlayerClient.All is actually an immutable collection. Magma, and later Fougerite, use the PlayerClient passed to the OnConnect hook to instance a Fougerite.Player object, and store it in a List, separate from PlayerClient.All.  But it's mutable.  And Magma/Fougerite remove the Player object from the List in OnDisconnect.  Which leads to concurrency problems if the List is accessed right when a player logs on or off.  You can't enumerate a mutable List while it is being modified.

The correct way to do this, which Newman class does, is to only instance Fougerite.Player on demand by selecting the client from PlayerClient.All. No more will a separate list Server.Players be kept (though I will make referencing it backwards compatible, and the rest of the old classes too, of course).

**Comment by mikecrews** [comment]
Turns out instancing new Fougerite.Player on demand won't work, because of reasons.
